name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  pv:  # id of input
    description: 'Kubernetes PV to mount'
    required: true
    default: ''
  sourcePath:  # id of input
    description: 'Folder to download from the PV'
    required: false
    default: ''
  destinationPath:  # id of input
    description: 'Folder to download the contents into'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pv }}
    - ${{ inputs.sourcePath }}
    - ${{ inputs.destinationPath }}
